# Generated by Django 4.1.3 on 2023-05-20 17:19

import budget.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0, verbose_name="Баланс")),
            ],
            options={
                "verbose_name": "Баланс",
                "verbose_name_plural": "Балансы",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Описание категории трат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="CategoryIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название категории"
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Слаг для категории дохода")),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Полное название валюты",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Буквенный код валюты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
                "default_related_name": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Наименование прихода"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Комментарий к приходу",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="Оприходованная сумму",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            5,
                            20,
                            17,
                            19,
                            36,
                            138520,
                            tzinfo=datetime.timezone.utc,
                        ),
                        validators=[budget.models.validate_date],
                        verbose_name="Время создания записи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приход средств",
                "verbose_name_plural": "Приходы средств",
            },
        ),
        migrations.CreateModel(
            name="MoneyBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=254, verbose_name="Цель накопления"),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000),
                        ],
                        verbose_name="Сумма, которую необходимо накопить",
                    ),
                ),
                (
                    "accumulation",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10000000),
                        ],
                        verbose_name="Уже накоплено",
                    ),
                ),
                (
                    "accumulated",
                    models.BooleanField(
                        default=False, verbose_name="Средств хватает чтобы закрыть цель"
                    ),
                ),
                (
                    "achieved",
                    models.BooleanField(
                        default=False, verbose_name="Цель достигнута/не достигнута"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Комментарий к приходу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель накопления",
                "verbose_name_plural": "Цели накопления",
            },
        ),
        migrations.CreateModel(
            name="Spend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=70, verbose_name="Наименование расхода"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        validators=[budget.models.validate_date],
                        verbose_name="Время создания записи",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="Израсходованная сумма",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Комментарий к расходу",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="budget.category",
                        verbose_name="Категория расхода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход средств",
                "verbose_name_plural": "Расходы средств",
                "default_related_name": "spends",
            },
        ),
    ]
