# Generated by Django 4.1.3 on 2023-05-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spend",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Траты пользователя",
            ),
        ),
        migrations.AddField(
            model_name="moneybox",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moneyboxes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Цель пользователя",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приходы пользователя",
            ),
        ),
        migrations.AddField(
            model_name="categoryincome",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_incomes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Категория дохода пользователя",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Категории созданные пользователем",
            ),
        ),
        migrations.AddField(
            model_name="balance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Баланс пользователя",
            ),
        ),
    ]
