# Generated by Django 4.1.3 on 2023-06-16 11:22

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budget", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="reapeatspend",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("to_date__isnull", True),
                    ("to_date__gte", models.F("created")),
                    _connector="OR",
                ),
                name="check_not_to_date_less_created",
                violation_error_message="Date before must be greater than or equal to the creation date",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="budget_category_name_unique",
                violation_error_message="Name must be unique!",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetfinance",
            constraint=models.UniqueConstraint(
                fields=("budget", "finance"),
                name="unique_budget_finance",
                violation_error_message="The funding source for the budget must be unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("budget"),
                models.F("category_type"),
                name="budget_budgetcategory_name_budget_category_type",
                violation_error_message="The budget category name must be unique!",
            ),
        ),
    ]
