# Generated by Django 4.1.3 on 2023-05-19 14:15

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={"verbose_name": "Баланс", "verbose_name_plural": "Балансы"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "default_related_name": "currencies",
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.AlterModelOptions(
            name="income",
            options={
                "verbose_name": "Приход средств",
                "verbose_name_plural": "Приходы средств",
            },
        ),
        migrations.AlterModelOptions(
            name="moneybox",
            options={
                "verbose_name": "Цель накопления",
                "verbose_name_plural": "Цели накопления",
            },
        ),
        migrations.AlterModelOptions(
            name="spend",
            options={
                "default_related_name": "spends",
                "verbose_name": "Расход средств",
                "verbose_name_plural": "Расходы средств",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="custom",
        ),
        migrations.AddField(
            model_name="moneybox",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Комментарий к приходу",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Описание категории трат",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="created",
            field=models.DateTimeField(
                validators=[budget.models.validate_date],
                verbose_name="Время создания записи",
            ),
        ),
        migrations.AlterField(
            model_name="spend",
            name="created",
            field=models.DateTimeField(
                validators=[budget.models.validate_date],
                verbose_name="Время создания записи",
            ),
        ),
        migrations.DeleteModel(
            name="UserCurrency",
        ),
    ]
