# Generated by Django 4.1.3 on 2023-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetcategory",
            name="default_use",
            field=models.BooleanField(
                default=False, verbose_name="default_use"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_use",
            field=models.BooleanField(
                default=False, verbose_name="default_use"
            ),
        ),
        migrations.AddField(
            model_name="finance",
            name="default_use",
            field=models.BooleanField(
                default=False, verbose_name="default_use"
            ),
        ),
    ]
