# Generated by Django 4.1.3 on 2023-05-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={
                "default_related_name": "incomes",
                "verbose_name": "Приход средств",
                "verbose_name_plural": "Приходы средств",
            },
        ),
        migrations.AlterModelOptions(
            name="moneybox",
            options={
                "default_related_name": "moneyboxes",
                "verbose_name": "Цель накопления",
                "verbose_name_plural": "Цели накопления",
            },
        ),
        migrations.RemoveField(
            model_name="categoryincome",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="moneybox",
            name="accumulated",
        ),
        migrations.AddField(
            model_name="categoryincome",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Комментарий к категории дохода",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budget.categoryincome",
                verbose_name="Категория дохода",
            ),
        ),
        migrations.AddField(
            model_name="moneybox",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budget.category",
                verbose_name="Категория расхода",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приходы пользователя",
            ),
        ),
    ]
