# Generated by Django 4.1.3 on 2023-05-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_remove_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spend',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Категории созданные пользователем'),
            preserve_default=False,
        ),
    ]
