# Generated by Django 4.1.3 on 2023-06-12 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget",
            "0003_budgetcategory_default_use_category_default_use_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetcategory",
            name="default_use",
        ),
    ]
