# Generated by Django 4.1.3 on 2023-06-01 09:16

from django.db import migrations, models

import colorfield.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget",
            "0003_alter_income_options_alter_moneybox_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=18,
                samples=None,
                unique=True,
                verbose_name="Цвет категории расхода",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="budget/", verbose_name="Иконка расхода"
            ),
        ),
    ]
