# Generated by Django 4.1.3 on 2023-06-17 17:05

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_rename_image_budgetcategory_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financetransaction",
            name="created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(
                        django.utils.timezone.now,
                        message="Creation date must not exceed the current date!",
                    )
                ],
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="moneybox",
            name="created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(
                        django.utils.timezone.now,
                        message="Creation date must not exceed the current date!",
                    )
                ],
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="reapeatspend",
            name="created",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MaxValueValidator(
                        django.utils.timezone.now,
                        message="Creation date must not exceed the current date!",
                    )
                ],
                verbose_name="created",
            ),
        ),
    ]
