# Generated by Django 4.1.3 on 2023-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0004_remove_budgetcategory_default_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetcategory",
            name="category_type",
            field=models.IntegerField(
                choices=[(0, "Income"), (1, "Expenses")],
                default=1,
                verbose_name="type",
            ),
        ),
    ]
