# Generated by Django 4.1.3 on 2023-06-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0005_moneybox_check_amount_less_accumulated"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.IntegerField(
                choices=[(1, "Expenses"), (2, "Income")],
                default=1,
                verbose_name="type",
            ),
        ),
        migrations.AddField(
            model_name="financetransaction",
            name="category_type",
            field=models.IntegerField(
                choices=[(1, "Expenses"), (2, "Income")],
                default=1,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="budgetcategory",
            name="category_type",
            field=models.IntegerField(
                choices=[(1, "Expenses"), (2, "Income")],
                default=1,
                verbose_name="type",
            ),
        ),
    ]
