# Generated by Django 4.1.3 on 2023-06-26 08:54

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_category_category_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financetransaction",
            name="name",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^([^\\W\\d_]| )+$"),
                        "Enter a valid string value consisting of only letters or space.",
                        "invalid",
                    ),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="name",
            ),
        ),
    ]
