# Generated by Django 4.1.3 on 2023-06-03 08:47

import django.core.validators
from django.db import migrations, models
import re
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="users", verbose_name="avatar"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=129,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator,
                    django.core.validators.MinLengthValidator(7),
                ],
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^([^\\W\\d_]|[\\s-])+$"),
                        "Enter a valid `name` value consisting of only letters and symbols `-`.",
                        "invalid",
                    )
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^([^\\W\\d_]|[\\s-])+$"),
                        "Enter a valid `name` value consisting of only letters and symbols `-`.",
                        "invalid",
                    )
                ],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                help_text="Required. 2-25 characters. Letters(a-z), digits and ./+/-/_ only.",
                max_length=25,
                unique=True,
                validators=[
                    users.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="username",
            ),
        ),
    ]
